language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - pip install sympy --use-mirrors
  - pip install numpy --use-mirrors
install:
  - python setup.py install
before_script:
  - cd sympybotics
script:
  - ../run_tests.sh
